# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0002_auto_20180130_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='daftartabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=500)),
                ('usia', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='daftartabel',
            name='pekerjaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabel.Pekerjaan'),
        ),
    ]
